 name: Deploy Scripts
 on:
   push:
     branches:
       - main
 jobs:
   deploy_scripts_s3:
     name: Copy scripts to s3
     runs-on: ubuntu-latest

     steps:
     - name: Checkout
       uses: actions/checkout@v2

     - name: Configure AWS credentials (dev)
       uses: aws-actions/configure-aws-credentials@v1
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

     - name: COPY SCRIPT
       uses: prewk/s3-cp-action@v2
       with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        source: './app'
        dest: ${{ secrets.AWS_BUCKET_NAME }}
        flags: --recursive